-- VISIOCAR AUTH SETUP & DEBUG
-- Run this in Supabase SQL Editor to verify/create test user

-- ============================================
-- STEP 1: Check if test user exists
-- ============================================
SELECT 
    id,
    email,
    email_confirmed_at,
    created_at,
    last_sign_in_at,
    raw_user_meta_data
FROM auth.users 
WHERE email LIKE '%test%'
ORDER BY created_at DESC
LIMIT 5;

-- ============================================
-- STEP 2: Create a test user directly (if needed)
-- Replace with your test email and password hash
-- ============================================

-- First, check if user exists
DO $$
DECLARE
    test_email TEXT := 'testuser@visiocar.com';
    test_user_id UUID;
BEGIN
    SELECT id INTO test_user_id 
    FROM auth.users 
    WHERE email = test_email;
    
    IF test_user_id IS NULL THEN
        -- Generate UUID
        test_user_id := gen_random_uuid();
        
        -- Create user with password 'TestPass123!'
        -- Password hash generated by Supabase
        INSERT INTO auth.users (
            id,
            email,
            encrypted_password,
            email_confirmed_at,
            raw_user_meta_data,
            created_at,
            updated_at,
            confirmation_sent_at,
            confirmed_at,
            last_sign_in_at,
            role,
            aud
        ) VALUES (
            test_user_id,
            test_email,
            crypt('TestPass123!', gen_salt('bf')),
            NOW(), -- Email already confirmed
            '{"full_name": "Test User"}',
            NOW(),
            NOW(),
            NOW(),
            NOW(),
            NOW(),
            'authenticated',
            'authenticated'
        );
        
        -- Create profile
        INSERT INTO profiles (id, email, full_name, created_at)
        VALUES (test_user_id, test_email, 'Test User', NOW())
        ON CONFLICT (id) DO NOTHING;
        
        RAISE NOTICE 'Test user created: %', test_email;
    ELSE
        RAISE NOTICE 'Test user already exists: %', test_email;
    END IF;
END $$;

-- ============================================
-- STEP 3: List all users with confirmation status
-- ============================================
SELECT 
    email,
    CASE 
        WHEN email_confirmed_at IS NOT NULL THEN '✅ Confirmed'
        ELSE '❌ Not Confirmed'
    END as confirmation_status,
    email_confirmed_at,
    created_at
FROM auth.users 
ORDER BY created_at DESC
LIMIT 10;

-- ============================================
-- STEP 4: RLS Policies Verification
-- ============================================
SELECT 
    schemaname,
    tablename,
    policyname,
    permissive,
    roles,
    cmd,
    qual
FROM pg_policies 
WHERE tablename IN ('profiles', 'garages', 'garage_members', 'claims')
ORDER BY tablename, policyname;